import ResetPasswordSection from "@/components/page-components/reset-password/ResetPasswordSection";
import Layout from "@/components/Layout/Layout";
import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";
import useUser from "@/lib/hooks/useUser";
import isEmpty from "@/utils/is-empty";

const ResetPasswordPage = () => {
  const router = useRouter();
  const user = useUser({ middleware: "guest", redirectIfAuthenticated: "/" });
  return (
    <>
      <Head>
        <title>Sign Up - Bangladesh ERP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ResetPasswordSection />
      </Layout>
    </>
  );
};

export default ResetPasswordPage;
