import React from "react";
import FetureCard from "./component/FetureCard";

const Features = () => {
  return (
    <section className="pb-20">
      <div className="container">
        <div className="grid gap-10 mt-5 md:gap-20 sm:grid-cols-2 md:mt-14">
          <FetureCard
            title="Shop Online"
            subtitle="You can online your Grocery shop integrated with your e-commerce platform which also our agile developer can make for you aas maintaining you're necessary . You can run your shop online with your live-stock management."
          />
          <FetureCard
            title="VAT Reports"
            subtitle="VAT reports generated by your grocery store billing software will assist you in filing taxes with ease. Entering all bills digitally into the system saves a lot of time and effort. Our system can assist you with the essential VAT reports whether you are in a regular or composition pattern."
          />
          <FetureCard
            title="Multiple Payment Mode"
            subtitle="Billing & real-time payment statuses are tracked & recorded from a single dashboard & have access to multiple payment modes."
          />
          <FetureCard
            title="Efficient Supply Orders"
            subtitle="Always keep an eye on low stock inventory reports through our and never run out of supplies. Within the app, you may set up notifications for low numbers of stock inventory items. It can assist you in placing your order before you run out of goods."
          />
          <FetureCard
            title="Loyalty Program"
            subtitle="Our Grocery shop billing software also has the Loyalty & Discount program module. We allow a loyalty program which is a type of incentive program that allows a company to collect information about its clients. Additionally, delivering product discount points to clients to attract customers. So this feature is ideal for your grocery shop billing software"
          />
          <FetureCard
            title="Day Closing"
            subtitle="Calculate you’re per day sales & purchase every day in the end time of closing the store, assume & maintain your monthly profits & losses."
          />
        </div>
      </div>
    </section>
  );
};

export default Features;
