/* eslint-disable react-hooks/rules-of-hooks */
import SignUpSection from "@/components/page-components/signup/SignUpSection";

import Layout from "@/components/Layout/Layout";
import Head from "next/head";
import React from "react";
import useUser from "@/lib/hooks/useUser";

const signup = () => {
  const user = useUser({ middleware: "guest", redirectIfAuthenticated: "/" });
  return (
    <>
      <Head>
        <title>Sign Up - Bangladesh ERP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SignUpSection />
      </Layout>
    </>
  );
};

export default signup;
