import CustomButton from "@/components/ui/Button";
import Layout from "@/components/Layout/Layout";
import { secureEmail } from "@/utils/email";
import Head from "next/head";
import React from "react";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import useUser from "@/lib/hooks/useUser";
import Button from "@/components/ui/Button";
import { useRouter } from "next/router";
import isEmpty from "@/utils/is-empty";

const ConfirmEmailPage = () => {
  const user = useUser({ middleware: "auth", redirectIfAuthenticated: "/" });
  const router = useRouter();

  console.log(user);

  return (
    <>
      <Head>
        <title>Bangladesh ERP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className="py-10">
          <div className="container text-center">
            <h1>
              {" "}
              Confirmation Email Has been sent to{" "}
              <span className="font-bold">
                {!isEmpty(user?.user.token) && secureEmail(user?.user?.email)}
              </span>{" "}
            </h1>
            <Button
              className="mt-5"
              onClick={() => {
                router.push("/");
              }}
            >
              Go To Home Page{" "}
              <ArrowForwardIcon className="ml-2" fontSize="small" />
            </Button>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default ConfirmEmailPage;
