import CustomButton from "@/components/ui/Button";
import Layout from "@/components/Layout/Layout";
import { secureEmail } from "@/utils/email";
import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import { useRouter } from "next/router";
import { useQuery } from "react-query";

const ConfirmEmailPage = () => {
  const [email, setEmail] = useState("");
  const router = useRouter();
  // eslint-disable-next-line react-hooks/exhaustive-deps

  useEffect(() => {
    const registerData = JSON.parse(localStorage.getItem("BDERP_register"));
    if (registerData) {
      console.log(registerData);
      setEmail(registerData.email);
    }
  });
  console.log(email);

  return (
    <>
      <Head>
        <title>Bangladesh ERP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className="py-10">
          <div className="container text-center">
            <h1>
              {" "}
              Confirmation Email Has been sent to{" "}
              <span className="font-bold">{secureEmail(email)}</span>{" "}
            </h1>
            <CustomButton
              className="mt-5"
              onClick={() => {
                router.push("/");
              }}
            >
              Go To Home Page{" "}
              <ArrowForwardIcon className="ml-2" fontSize="small" />
            </CustomButton>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default ConfirmEmailPage;
