import BusinessGrowth from "@/components/home/BusinessGrowth";
import HeroInput from "@/components/home/HeroInput";
import HeroSection from "@/components/home/HeroSection";
import Layout from "@/components/ui/Layout";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout transparent>
        <HeroSection />

        <BusinessGrowth />
      </Layout>
    </>
  );
}
