import ExclusiveFeature from "@/components/page-components/feature/ExclusiveFeature";
import FeatureComparison from "@/components/page-components/feature/FeatureComparison";
import FeatureSection from "@/components/page-components/feature/FeatureSection";
import Hero from "@/components/page-components/feature/Hero";
import TableSection from "@/components/page-components/feature/TableSection";
import Layout from "@/components/ui/Layout";
import Head from "next/head";
import React from "react";

const feature = () => {
  return (
    <>
      <Head>
        <title>Sign Up - Bangladesh ERP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <FeatureSection />
        <FeatureComparison />
        <ExclusiveFeature />
        <TableSection />
      </Layout>
    </>
  );
};

export default feature;
